Amd64

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -66,8 +66,13 @@ jobs:
             python${{ matrix.python_version }}-venv \
             python3-pip \
             build-essential lld git zip unzip pkg-config curl
-          python${{ matrix.python_version }} -m venv /tmp/tflite_env
-          . ./tmp/tflite_env/bin/activate
+          python3 -m venv /tmp/tflite_env
+          if [ ! -d "/tmp/tflite_env/bin" ]; then
+              echo "Error: Virtual environment was not created successfully."
+              ls -l /tmp
+              exit 1
+          fi
+          source /tmp/tflite_env/bin/activate
           pip install --upgrade pip wheel numpy==1.26.4 auditwheel setuptools
 
       - name: Configure arm64 Repositories
@@ -79,7 +84,7 @@ jobs:
         shell: bash    
         run: |
           set -xe
-          . ./tmp/tflite_env/bin/activate
+          source /tmp/tflite_env/bin/activate
           python --version        
           export PYTHON_VERSION="${{ matrix.python_version }}"
           export TF_PYTHON_VERSION="$PYTHON_VERSION"
